version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  teamcity:
    image: jetbrains/teamcity-server
    environment:
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx1024M # "-Xmx350m -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
      - TEAMCITY_HTTPS_PROXY_ENABLED=true
    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs
      - teamcity-conf:/opt/teamcity/conf
    depends_on:
      - db

  nginx:
    depends_on:
      - teamcity
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./ssl
        target: /ssl
        read_only: true
    ports:
      - "443:443"

  teamcity-build-agent:
    image: jastenewname/android-build-agent
    user: "1000:${GID}"
    environment:
      - TEAMCITY_AGENT_MEM_OPTS=-Xmx512M
      - SERVER_URL=teamcity:8111
    volumes:
      - agent-1-config:/data/teamcity_agent/conf
      - agent-1-work:/opt/buildagent/work
      - agent-1-system:/opt/buildagent/system
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

volumes:
  postgresql-data:
  teamcity-data:
  teamcity-logs:
  teamcity-conf:
  agent-1-config:
  agent-1-work:
  agent-1-system:
