version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  teamcity:
    image: jetbrains/teamcity-server
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx1024m"
    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs
      - teamcity-conf:/opt/teamcity/conf
    ports:
      - "8111:8111"
    depends_on:
      - db

volumes:
  postgresql-data:
  teamcity-data:
  teamcity-logs:
  teamcity-conf:
